services:

  api:
    build:
      context: ./Ecommerce.Api
      dockerfile: Dockerfile
    container_name: ecommerce_api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      JWT__Key: ${JWT_KEY}
    ports:
      - "5046:8080"
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ecommerce_frontend
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped